parser: babel-eslint

extends: airbnb

env:
  browser: true

rules:
  react/jsx-filename-extension: off
  import/no-extraneous-dependencies: off
  # import/no-extraneous-dependencies:
  #   - error
  #   - devDependencies: true
  #     optionalDependencies: false
  #     peerDependencies: false
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never

# settings:
#   import/resolver:
#     webpack:
#       config: webpack.config.eslint.js
