os:
  - osx

language: node_js
node_js:
- '6'

env:
  global:
    # GH_TOKEN=xxxxxxxxxxxxxxxxxx
    - secure: "o/klHmioR1iHcNoshZlTiolp6CJY0mFBomKcWeio67lhvfPHGMffY7p1yfqKch6NDlx3qXfGSE05SVVRX5DY8/NwViwLaqh2Y5MvzphCz76qU6ViVsX/IRUb6DM8AAY6NCztxzn33qxOWsf3B9G55TiTvLurQYt+ofJRpHDyLH6fE544NFce2PRvNs+htvhQdyv+3Us5JiBq1Lye2BUNdw0Qnd34T+MvN5NcwZ/s8rtJu5n9T1K0u7QRi7N/6xJkldWX0F+ZDPr6nzzwAL0XuzIHsbJpmFcX3aTVnKmEblNHToWcGLGbSvTACe5FvyJsjauiEiWWXHGG3ZeYtx6QFd+klAbqpFfilfVOA4GPo3+pdHeX+lIe+zja6XeV3epsK/JF3+NUbot+ReXJ+NvzTiobR++2mlOZ4XnbImre8+xu6v2ieoqyLf1w+8eb8+SfnYMqSl3IsbRcP5x1jhy5KduLbrnOL55W9XteU6BIUA67v11RRQqfMPv+BBzLFK1fo3S09VDeaBdjm2Yp+V1ZncCFgokxdyqeYkWWb4Z8ooMHnCIDoAxgmr6oiVIpBnORHuwZK4jqezEpOoLyzk5CqvcbHISrKwjWAx4OsRks6HHVl5RVPZF6haI7xYtWvmPk8uOK21dQcYWO+hL7YyTFa6ZSTH8IkxqbCMpqfy/ZOy4="

cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"

after_success:
  - npm run dist
