language: node_js

node_js:
- '6'

os:
- osx

env:
  global:
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache

script:
- npm run lint
